default: &default
  adapter: postgis
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: felipe
  password: 123123
  host: localhost

development:
  <<: *default
  database: find_my_coffee_development
test:
  <<: *default
  database: find_my_coffee_test

production:
  <<: *default
  database: find_my_coffee_production
  username: find_my_coffee
  password: <%= ENV['FIND_MY_COFFEE_DATABASE_PASSWORD'] %>
